version: '3.7'

services:
  db:
    container_name: todo-list-db-container
    image: postgres
    volumes:
      - postgres_data:/api/db/
    environment:
      POSTGRES_PASSWORD: $PSQL_PASSWORD
      POSTGRES_USER: $PSQL_USER
      POSTGRES_DB: $PSQL_NAME
  api:
    container_name: todo-list-api-container
    environment:
      PORT: $PORT
    build: ./api      
    command: bash -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    depends_on:
      - db
  front:
    container_name: todo-list-front-container
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

volumes:
  postgres_data:

  

